version: '2.6'

services:

  db:
    image: postgres:13.0-alpine
    environment:
      - POSTGRES_PASSWORD: mypassword
      - POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: alice08/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - docs:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: alice08/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    restart: always

volumes:
  static_value:
  media_value:
  postgres_data:
  docs:
